- hosts: localhost
  pre_tasks:
    - name: Update - Ubuntu
      tags: always
      when: ansible_facts['distribution'] == "Ubuntu"
      become: true
      apt:
        update_cache: true

    - name: Update - MacOS
      tags: always
      when: ansible_facts['os_family'] == "Darwin"
      become: false
      block:
        # ref: https://opensource.com/article/22/6/install-software-macos-ansible-homebrew
        - name: Check homebrew - MacOS
          stat:
            path: /opt/homebrew/bin/brew
          register: homebrew_check

        # ref: https://brew.sh/
        - name: Install homebrew - MacOS
          when: not homebrew_check.stat.exists
          shell: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/{{ sha }}/install.sh)"
          vars:
            # as of 2023-02-13
            sha: fc4a19b38608451cabe6ceaa8ffb4fa1300854c8  

        - name: Update homebrew - MacOS
          community.general.homebrew:
            update_homebrew: true

  tasks:
    - import_tasks: ansible-tasks/python.yml
    - import_tasks: ansible-tasks/quarto.yml
    - import_tasks: ansible-tasks/R.yml
    - import_tasks: ansible-tasks/gh.yml 
    - import_tasks: ansible-tasks/zsh.yml
    - import_tasks: ansible-tasks/ohmyzsh.yml
