- name: Install ohmyzsh
  tags: ohmyzsh, dev
  become: false
  # ref: beginning of https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  block:
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: file
        suffix: .sh
      register: install_tempfile

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ install_tempfile.path }}"
        mode: "guo+x"

    - name: Install ohmyzsh
      shell: |
        {{ install_tempfile.path }}
      args:
        executable: /bin/sh

    - name: Delete temporary file
      ansible.builtin.file:
        path: "{{ install_tempfile.path }}"
        state: absent
      when: install_tempfile.path is defined

  # ref: https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#oh-my-zsh
- name: Install zsh-autosuggestions
  tags: ohmyzsh, zshauto
  become: false
  ansible.builtin.git: 
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"