- name: Check for ohmyzsh
  become: false
  stat:
    path: "~/.oh-my-zsh"
  register: ohmyzsh_path

- name: Install ohmyzsh
  tags: ohmyzsh, dev
  when: ohmyzsh_path.stat.exists == false
  become: false
  # ref: beginning of https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  block:
    - name: Create temporary file
      ansible.builtin.tempfile:
        state: file
        suffix: .sh
      register: install_tempfile

    - name: Download ohmyzsh
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
        dest: "{{ install_tempfile.path }}"
        mode: "guo+x"

    - name: Install ohmyzsh
      shell: |
        {{ install_tempfile.path }}
      args:
        executable: /bin/sh

    - name: Delete temporary file
      ansible.builtin.file:
        path: "{{ install_tempfile.path }}"
        state: absent
      when: install_tempfile.path is defined

- name: zsh-autosuggestions
  tags: zshauto, ohmyzsh, dev 
  vars:
    zshauto_dir: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  block:       
    - name: Check for zsh-autosuggestions
      become: false
      stat:
        path: zshauto_dir
      register: zshauto_path

      # ref: https://github.com/zsh-users/zsh-autosuggestions/blob/master/INSTALL.md#oh-my-zsh
    - name: Install zsh-autosuggestions
      become: false
      when: zshauto_path.stat.exists == flase
      ansible.builtin.git: 
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: zshauto_dir