# ref: https://github.com/pyenv/pyenv-installer
- name: Install pyenv
  tags: pyenv
  become: false
  block:
    - name: Install pyenv - Ubuntu
      when: |
        ansible_facts['distribution'] == "Ubuntu" and (
          ansible_facts['distribution_major_version'] == "20" or
          ansible_facts['distribution_major_version'] == "22"
        )
      vars:
        # as of 2023-02-14
        hash: f971e5d01ac2cba8be2ebe97c652506d90185807        
      shell: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/{{ hash }}/bin/pyenv-installer | 
            bash

    - name: Install pyenv - MacOS
      when: ansible_facts['os_family'] == "Darwin"
      community.general.homebrew:
        name: pyenv
        state: present

- name: Update login scripts for pyenv
  tags: pyenv
  become: false
  vars:
    # using `--enable-shared` to support reticulate: 
    #   https://rstudio.github.io/reticulate/articles/versions.html#locating-python
    pyenv_config: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      export PYTHON_CONFIGURE_OPTS="--enable-shared"
  block:
    - name: Amend .bashrc
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        create: true
        block: "{{ pyenv_config }}"
    
    - name: Amend .profile
      ansible.builtin.blockinfile:
        path: ~/.profile
        create: true
        block: "{{ pyenv_config }}"
     
    - name: Amend .zshrc
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        create: true
        block: "{{ pyenv_config }}"
     
    - name: Amend .zprofile
      ansible.builtin.blockinfile:
        path: ~/.zprofile
        create: true
        block: "{{ pyenv_config }}"

- name: Manage Python installations
  tags: python
  vars:
    python_version: 3.11.2
  block:      
    - name: Install Python
      shell: |
        pyenv install -s {{ python_version }}
      args:
        executable: /bin/bash

    - name: Set default version of Python
      shell: |
        pyenv global {{ python_version }}
      args:
        executable: /bin/bash


