- name: Install quarto using qvm
  tags: quarto, data
  vars:
    quarto_version: release
    qvm_version: "0.3.0"
    qvm_config: |
      export PATH="$(qvm path add)"
  block:
    # ref: https://github.com/dpastoor/qvm/releases
    - name: Install qvm (ubuntu)
      when: ansible_facts['distribution'] == "Ubuntu"
      become: true
      shell: |
        wget https://github.com/dpastoor/qvm/releases/download/v{{ qvm_version }}/qvm_Linux_x86_64.tar.gz -O /tmp/qvm.tar.gz 
        tar xzf /tmp/qvm.tar.gz qvm 
        mv qvm /usr/local/bin/qvm 
        chmod +x /usr/local/bin/qvm 
      args:
        executable: /bin/bash

    # ref: https://github.com/dpastoor/qvm/releases
    - name: Install qvm (macOS)
      when: ansible_facts['os_family'] == "Darwin"
      become: false
      community.general.homebrew_tap:
        name: dpastoor/tap/qvm
        state: present

    - name: Update login scripts for qvm
      become: false
      block:
        - name: Amend .bashrc
          ansible.builtin.blockinfile:
            path: ~/.bashrc
            create: true
            block: "{{ qvm_config }}"
        
        - name: Amend .profile
          ansible.builtin.blockinfile:
            path: ~/.profile
            create: true
            block: "{{ qvm_config }}"
        
        - name: Amend .zshrc
          ansible.builtin.blockinfile:
            path: ~/.zshrc
            create: true
            block: "{{ qvm_config }}"
        
        - name: Amend .zprofile
          ansible.builtin.blockinfile:
            path: ~/.zprofile
            create: true
            block: "{{ qvm_config }}"

    # ref: https://github.com/dpastoor/qvm#installing-versions
    - name: Install quarto
      become: false
      shell: |
        /usr/local/bin/qvm install {{ quarto_version }} 
        /usr/local/bin/qvm use {{ quarto_version }}    
      args:
        executable: /bin/bash