name: Ansible - Walkthrough

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    # macOS runtimes can be long: restrict to changes in ansible files
    paths: ['local.yml', 'ansible-tasks/**.yml']

jobs:
  ansible:
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} 

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            sudo apt update
            sudo apt install software-properties-common
            sudo add-apt-repository --yes --update ppa:ansible/ansible
            sudo apt install ansible
          elif [ "${{ runner.os }}" == "macOS" ]; then
            # workaround ref: https://github.com/actions/setup-python/issues/577#issuecomment-1500828576
            rm /usr/local/bin/2to3 || true
            rm /usr/local/bin/2to3-3.11 || true
            rm /usr/local/bin/idle3 || true
            rm /usr/local/bin/idle3.11 || true
            rm /usr/local/bin/pydoc3 || true
            rm /usr/local/bin/pydoc3.11 || true            
            rm /usr/local/bin/python3-config || true
            rm /usr/local/bin/python3.11-config || true            
            rm /usr/local/bin/python3 || true
            rm /usr/local/bin/python3.11 || true

            brew update
            brew install ansible
          else
            echo "${{ runner.os }} not supported"
            exit 1
          fi
        shell: bash 

      - name: Install data tools
        run: |
          ansible-playbook local.yml --tags "R, python, quarto" -e "ansible_become_password=''"
        shell: bash 

      - name: Establish pyenv
        # using `--enable-shared` to support reticulate: 
        #   https://rstudio.github.io/reticulate/articles/versions.html#locating-python
        run: |
          echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV
          echo "$HOME/.pyenv/bin" >> $GITHUB_PATH
          echo "$HOME/.pyenv/shims" >> $GITHUB_PATH
          echo "PYTHON_CONFIGURE_OPTS=--enable-shared" >> $GITHUB_ENV
        shell: bash

      - name: Check data tools
        run: |
          rig list
          pyenv versions
          quarto check
        shell: bash     

      - name: Install development tools
        run: |
          ansible-playbook local.yml --tags "zsh, ohmyzsh, gh, stow" -e "ansible_become_password=''"
        shell: bash 

      - name: Check default shell
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            grep "^$(whoami)" /etc/passwd
          elif [ "${{ runner.os }}" == "macOS" ]; then
            dscl . -read ~/ UserShell
          else
            echo "${{ runner.os }} not supported"
            exit 1
          fi          
        shell: bash

      - name: Check oh-my-zsh
        run: |
          ls -l ~/.oh-my-zsh
          ls -l ~/.oh-my-zsh/custom/plugins
        shell: bash

      - name: Check development tools
        run: |
          gh --version
          stow --version
        shell: bash    
