name: Docker - Orchestrate Build and Push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    # runtimes can be long: restrict to changes in docker directory
    paths: ['docker-images/**']

jobs:
  base:
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: base
    permissions:
      contents: read
      packages: write

  batch:
    needs: base
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: batch
    permissions:
      contents: read
      packages: write

  active:
    needs: batch
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: active
    permissions:
      contents: read
      packages: write       