name: Build and Push Image

on:
  workflow_call:
    inputs:
      level:
        required: true
        type: string  

env:
  REGISTRY: ghcr.io

jobs:
  build-push-by-distribution: 
    runs-on: ubuntu-latest  

    strategy:
      fail-fast: false
      matrix:
        dist: ['focal', 'jammy'] 
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create temporary buildx builder
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata 
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.level }}
          flavor: |
            suffix=-${{ matrix.dist }}
          tags: |
            type=edge
            type=schedule,pattern=weekly
            type=ref,event=pr

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          platforms: 'linux/amd64'
          context: docker-images/${{ inputs.level }}
          push: true
          build-args: |
            IMAGE_VERSION=${{ steps.meta.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
