name: Docker - Orchestrate Build and Push

on:
  schedule: 
    - cron: '15 15 * * 6' # 15h15 UTC every Saturday
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    # runtimes can be long: restrict to changes within specified directories
    # paths: ['docker-images/**', '.github/workflows/**.yml']

jobs:
  base:
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: base
    permissions:
      contents: read
      packages: write

  batch:
    needs: base
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: batch
    permissions:
      contents: read
      packages: write

  active:
    needs: batch
    uses: ./.github/workflows/docker-build-push-image.yml
    with:
      level: active
    permissions:
      contents: read
      packages: write       